### ISSUE TITLE
Vignettes don't build from install_github

### ISSUE THREAD

**Issue by zkamvar** [knausb/vcfR_docs#1]
When installing from github, the vingettes don't build

``` r
devtools::install_github("knausb/vcfR_docs", build_vignettes = TRUE)
browseVignettes("vcfRdocs")
#> No vignettes found by browseVignettes("vcfRdocs")
```

I suspect that the culprit is the fact that you don't have a `VignetteBuilder:` field in your DESCRIPTION file.

**Comment by knausb** [comment]
That brought a few other issues to light. Should be fixed in 7f4e21a59f14bfc5ae7980f5c9eb5e85050289f0.

Thanks!
